import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className="bg-gray-50 text-gray-800">
                <header className="shadow-sm bg-white">
                    <div className="max-w-6xl mx-auto px-6 py-4 flex items-center justify-between">
                        <Link href="/">
                            <h1 className="text-2xl font-bold text-indigo-600">
                                Shoply
                            </h1>
                        </Link>
                        <nav className="space-x-4">
                            <Link href="/" className="text-sm">
                                Home
                            </Link>
                            <Link href="/dashboard" className="text-sm">
                                Dashboard
                            </Link>
                            <Link href="/admin" className="text-sm">
                                Admin
                            </Link>
                            <Link href="/recommendations" className="text-sm">
                                Recommendations
                            </Link>
                        </nav>
                    </div>
                </header>
                <main className="w-full mx-auto px-6 py-8">{children}</main>
                <footer className="text-center text-sm text-gray-500 py-8">
                    Built for assignment
                </footer>
            </body>
        </html>
    );
}
